cargo: bump ring to 0.11
This updates to latest ring to interop with crates depending on newer
versions. In particular this avoid linking error like:
```
error: native library `ring-asm` is being linked to by more than one
version of the same package, but it can only be linked once; try updating
or pinning your dependencies to ensure that this package only shows up once

  ring v0.9.7
  ring v0.11.0
```